########################
### Sample API documents
########################
sampleapidoc:
  describe:
    sample:
      post: |
        サンプルのPOSTメソッドです。入力されたクレデンシャル情報を検証し、認証の成否を返します。
      get: |
        サンプルのGETメソッドです。入力された名前に対してメッセージを返します。
      redirect: |
        サンプルのリダイレクトです。googleトップページにリダイレクトします。
